import './App.css'

const Arrow = () => <span aria-hidden="true">↗</span>

function Network() {
  const nodes = [{x:95,y:170},{x:180,y:80},{x:190,y:270},{x:300,y:165},{x:345,y:60},{x:390,y:300},{x:495,y:140},{x:510,y:255}]
  const edges = [[0,1],[0,2],[0,3],[1,3],[1,4],[2,3],[2,5],[3,4],[3,5],[3,6],[4,6],[5,6],[5,7],[6,7]]
  return <div className="network-panel" aria-label="Diagram of interconnected nodes representing artificial intelligence and information networks">
    <div className="diagram-top"><span>EXPLORING THE CONNECTIONS</span><span className="cross">+</span></div>
    <svg viewBox="0 0 600 360" role="img" aria-label="An interconnected network with intelligence at its center">
      <defs><pattern id="dots" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#34424b"/></pattern><radialGradient id="glow"><stop stopColor="#c9ac65" stopOpacity=".14"/><stop offset="1" stopColor="#c9ac65" stopOpacity="0"/></radialGradient></defs>
      <rect width="600" height="360" fill="url(#dots)"/><circle cx="300" cy="165" r="150" fill="url(#glow)"/>
      {edges.map(([a,b],i)=><line key={i} x1={nodes[a].x} y1={nodes[a].y} x2={nodes[b].x} y2={nodes[b].y} stroke={a===3||b===3?'#b59b61':'#46535c'} strokeOpacity=".65"/>)}
      {nodes.map((n,i)=><g key={i}><circle cx={n.x} cy={n.y} r={i===3?19:9} fill="#10202b" stroke={i===3?'#dfc17d':'#8b999f'} /><circle cx={n.x} cy={n.y} r={i===3?6:3} fill={i===3?'#dfc17d':'#8b999f'}/></g>)}
      <text x="300" y="211" textAnchor="middle">INTELLIGENCE</text><text x="95" y="204" textAnchor="middle">DATA</text><text x="492" y="114" textAnchor="middle">NETWORKS</text>
    </svg>
    <div className="diagram-bottom"><span><i/> Two threads. One connected perspective.</span><span>01 / 02</span></div>
  </div>
}

const projects = [
  { title: 'RAG Study Assistant', category: 'TEAM PROJECT · IN PROGRESS', description: 'Turning course materials into context-aware explanations, practice tests, and flashcards. Collaborating on an asynchronous document-processing and retrieval pipeline for semantic search and personalized weak-point tracking.', stack: ['TypeScript', 'React', 'Express', 'Redis', 'BullMQ', 'PostgreSQL'] },
  { title: 'AI Research Agent', category: 'AI & AUTOMATION · IN PROGRESS', description: 'Building an agent that plans research, searches the web, evaluates sources, and produces cited reports. Engineered a Redis and BullMQ pipeline that revises queries and launches follow-up searches to close gaps in evidence.', stack: ['TypeScript', 'React', 'Express', 'Exa', 'Redis', 'BullMQ'] },
  { title: 'Bond', category: 'SOCIAL PLATFORM · JUL 2026', description: 'Built a social platform with real-time messaging and responsive UI state. Designed friend suggestions using two-hop BFS over the follow graph and direct image uploads with presigned Cloudflare R2 URLs.', stack: ['React', 'TypeScript', 'PostgreSQL', 'Socket.io', 'TanStack Query', 'Zustand'] },
  { title: 'myCloud', category: 'CLOUD STORAGE · MAY 2026', description: 'Built a subscription-based cloud storage app with Firebase authentication and user management, direct uploads to Cloudflare R2, and Stripe subscriptions.', stack: ['TypeScript', 'Next.js', 'Firebase', 'Stripe', 'Cloudflare R2'] },
]
const additionalProjects = [
  { title: 'Salary Prediction Model', date: 'MAR 2026', description: 'An end-to-end Python ML pipeline using KMeans geographic clustering, a scikit-learn ColumnTransformer, and 10-fold cross-validated RMSE to evaluate linear regression and random forest models.' },
  { title: 'Navigation System', date: 'MAR 2025', description: 'A C++ shortest-path program using Dijkstra’s algorithm, with an A* prototype.' },
  { title: '6 Degrees of Separation', date: 'DEC 2024', description: 'A C++ breadth-first search over the IMDb dataset, using graphs, hash maps, and vectors to explore connections.' },
]

function App() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header wrap"><a className="wordmark" href="#" aria-label="Zaw Lin Than home">zlt<span>.</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a className="nav-contact" href="#opportunities">Let’s connect <Arrow/></a></nav></header>
    <main id="main">
      <section className="hero wrap" aria-labelledby="hero-title">
        <div className="hero-copy"><div className="eyebrow"><span className="gold-line"/> COMPUTER SCIENCE @ GEORGIA TECH</div><h1 id="hero-title">Hi, I’m<br/>Zaw Lin Than<span className="gold">.</span></h1><p className="hero-lead">Curious about intelligence.<br/>Inspired by connection.</p><p className="hero-description">I build AI tools and full-stack applications. At Georgia Tech, I’m exploring artificial intelligence and the networks that connect our world.</p><a href="#projects" className="button">Explore my work <span aria-hidden="true">↓</span></a><a className="text-link" href="/Zaw-Lin-Than-Resume.pdf" download>Download résumé <span aria-hidden="true">↓</span></a></div>
        <div className="hero-visual"><div className="availability"><i/> OPEN TO INTERNSHIPS & CO-OPS</div><Network/><div className="visual-caption"><span>AI × INFORMATION INTERNETWORKS</span><span>ATLANTA, GA</span></div></div>
      </section>
      <div className="facts wrap"><div><span className="fact-label">CURRENTLY</span><span>B.S. Computer Science · Expected May 2028</span></div><div><span className="fact-label">AT</span><span>Georgia Institute of Technology</span></div><div><span className="fact-label">LOOKING FOR</span><span>Internships & co-ops <span className="gold">↗</span></span></div></div>
      <section id="about" className="about wrap section"><div className="section-label"><span>01</span> ABOUT ME</div><div><h2>Learning how things think.<br/><span className="muted">Understanding how they connect.</span></h2><div className="about-body"><p>I’m pursuing a B.S. in Computer Science at Georgia Tech, concentrating in Artificial Intelligence and Information Internetworks. Previously, I earned an A.S. in Computer Science at Santa Monica College with a 4.0 GPA.</p><p>From AI research pipelines to real-time messaging, I enjoy turning ideas into working software. As a project manager at GT WebDev, I’m also leading a team building an AI study assistant. I’m seeking an internship or co-op where I can contribute and keep growing.</p></div></div></section>
      <section id="projects" className="projects wrap section"><div className="section-heading"><div><div className="section-label"><span>02</span> SELECTED PROJECTS</div><h2>Ideas, put into practice.</h2></div><a className="text-link" href="https://github.com/ZawLinThan" target="_blank" rel="noreferrer">Explore my GitHub <Arrow/></a></div><div className="focus-grid">{projects.map((project, index) => <article className="focus-card project-card" key={project.title}><div className="card-top"><span className="project-number">0{index + 1}</span><span>{project.category}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.stack.map(skill => <span key={skill}>{skill}</span>)}</div></article>)}</div><details className="more-projects"><summary>More projects in machine learning & algorithms <span aria-hidden="true">＋</span></summary><div className="additional-grid">{additionalProjects.map(project => <article key={project.title}><span className="fact-label">{project.date}</span><h3>{project.title}</h3><p>{project.description}</p></article>)}</div></details></section>
      <section id="focus" className="focus wrap section"><div className="section-heading"><div><div className="section-label"><span>03</span> AREAS OF FOCUS</div><h2>Two threads.<br/>A connected perspective.</h2></div><p>Exploring the ideas behind smarter systems<br className="desktop-break"/> and a more connected world.</p></div><div className="focus-grid"><article className="focus-card"><div className="card-top"><span className="card-icon" aria-hidden="true">✳</span><span>THREAD / 01</span></div><h3>Artificial Intelligence</h3><p>Understanding how computational systems learn, reason, and use information to solve problems.</p><div className="tags"><span>Intelligent systems</span><span>Learning & reasoning</span></div></article><article className="focus-card"><div className="card-top"><span className="card-icon network-icon" aria-hidden="true">⌘</span><span>THREAD / 02</span></div><h3>Information Internetworks</h3><p>Exploring how information moves through networks and how connected systems work together.</p><div className="tags"><span>Connected systems</span><span>Information networks</span></div></article></div></section>
      <section id="skills" className="skills wrap section"><div className="section-label"><span>04</span> TOOLKIT</div><h2>What I work with.</h2><div className="skill-grid"><div><h3>Languages</h3><p>Python · C++ / C · Java · JavaScript · TypeScript</p><p className="skill-note">Familiar with SQL</p></div><div><h3>AI & data</h3><p>scikit-learn · pandas · NumPy · Jupyter · Matplotlib</p></div><div><h3>Web & infrastructure</h3><p>React · Node.js · Next.js · TanStack Query · Zustand · PostgreSQL · Drizzle ORM · Firebase · Git</p></div></div><div className="coursework"><span className="fact-label">COMPLETED COURSEWORK</span><p>Data Structures & Algorithms · Linear Algebra · Discrete Math · Multivariable Calculus · Digital System Design</p></div></section>
      <section id="experience" className="experience wrap section"><div className="section-heading"><div><div className="section-label"><span>05</span> EXPERIENCE & LEADERSHIP</div><h2>Building with people.</h2></div></div><div className="timeline"><article><div><span className="fact-label">SEP 2026 — PRESENT</span><h3>Project Manager</h3><span>GT WebDev · Georgia Tech</span></div><p>Leading a team of five on a full-stack AI Study Assistant project using retrieval-augmented generation.</p></article><article><div><span className="fact-label">FEB 2025 — JUN 2026</span><h3>Vice President of Scholarship</h3><span>Phi Theta Kappa · Santa Monica College</span></div><p>Revived the chapter tutoring program with seven tutors and coordinated scholarship workshops.</p></article><article><div><span className="fact-label">SEP 2025 — JAN 2026</span><h3>Research Project Lead</h3><span>Phi Theta Kappa · Honors in Action</span></div><p>Directed a multidisciplinary team of four through the research project cycle, achieving third place in the Nevada/California region.</p></article><article><div><span className="fact-label">FEB 2025 — NOV 2025</span><h3>Shift Lead</h3><span>Melo Melo Coconut Dessert · Los Angeles</span></div><p>Developed an Excel inventory system deployed across 11 stores to improve stock tracking and reduce food waste. Oversaw daily operations and trained staff.</p></article><article><div><span className="fact-label">MAR 2025 — JUN 2025</span><h3>Website Committee</h3><span>Alpha Gamma Sigma · Santa Monica College</span></div><p>Maintained, updated, and edited the honor society’s website.</p></article></div><div className="honors"><h3>Honors & awards <span className="gold">↗</span></h3><ul><li>3rd Place, Honors in Action Research Project <span>Phi Theta Kappa · NV/CA Region · 2026</span></li><li>Jack Kent Cooke Transfer Scholarship Semifinalist <span>Jack Kent Cooke Foundation · 2026</span></li><li>6th Place, AMATYC Student Math League <span>College level · Santa Monica College · 2026</span></li></ul></div></section>
      <section id="opportunities" className="opportunities wrap"><div className="section-label"><span>06</span> LET’S CONNECT</div><div className="opportunities-content"><div><div className="availability"><i/> SEEKING INTERNSHIPS & CO-OPS</div><h2>Ready to learn.<br/>Ready to contribute<span className="gold">.</span></h2></div><p>I’m looking for opportunities to bring my curiosity and computer science education to real-world challenges.<br/><br/>Interested in artificial intelligence, connected systems, and the problems in between.</p></div><div className="contact-links"><a className="button" href="mailto:zthan3@gatech.edu">zthan3@gatech.edu <Arrow/></a><a href="https://github.com/ZawLinThan" target="_blank" rel="noreferrer">GitHub <Arrow/></a><a href="/Zaw-Lin-Than-Resume.pdf" download>Download résumé ↓</a></div><p className="spoken-languages">English & Mandarin — proficient · Burmese — native</p></section>
    </main>
    <footer className="wrap"><a className="wordmark" href="#">zlt<span>.</span></a><span>© {new Date().getFullYear()} Zaw Lin Than</span><a href="#">Back to top ↑</a></footer>
  </>
}
export default App
